USE [master]
GO

/****** Object:  Database [PRUEBADB]    Script Date: 24/06/2021 12:47:59 a. m. ******/
CREATE DATABASE [PRUEBADB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'pruebadb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\pruebadb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'pruebadb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\pruebadb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRUEBADB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRUEBADB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRUEBADB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRUEBADB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRUEBADB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRUEBADB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRUEBADB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRUEBADB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRUEBADB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRUEBADB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRUEBADB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRUEBADB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRUEBADB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRUEBADB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRUEBADB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRUEBADB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRUEBADB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRUEBADB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRUEBADB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRUEBADB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRUEBADB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRUEBADB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRUEBADB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRUEBADB] SET RECOVERY FULL 
GO

ALTER DATABASE [PRUEBADB] SET  MULTI_USER 
GO

ALTER DATABASE [PRUEBADB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRUEBADB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRUEBADB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRUEBADB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PRUEBADB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRUEBADB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PRUEBADB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PRUEBADB] SET  READ_WRITE 
GO

