USE [PRUEBADB]
GO

/****** Object:  Table [dbo].[auditoria]    Script Date: 24/06/2021 12:48:23 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[auditoria](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fecha_hora] [datetime] NULL,
	[descripcion] [varchar](200) NULL,
 CONSTRAINT [PK_auditoria] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

